### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by cideM** [P215W/eloqJs#1]
None of the exercises have tests, write some please. I would start by looking at https://nodejs.org/api/assert.html before checking out libraries such as `ava` or `tape`. It's going to be tricky writing tests for something that just does `console.log`. Maybe we can extract a pure function (what are pure functions?) from it, test that, and simply `console.log` the output of that function. 

Filenames with spaces are very uncommon, I'd call it `ex1_chessboard.js` or something like that.

https://github.com/P215W/eloqJs/blob/master/ex1%20-%20loopingTriangle.js#L3 is nice for creating triangles with `#`, but what if I want to use `!` or something else? Would be nice if it could be passed as a parameter to the function. But what if I'm not a developer but I want to use your function from the command line? As a bonus exercise, look into calling your script from the command line (what does `#!/usr/bin/node` do?) https://nodejs.org/api/process.html#process_process_argv might help. 

I want to do something like

```shell
$ chessboard --symbol #
```

and have it print its output.

**Comment by P215W** [comment]
@cideM 

Found less time than expected during the last week, espec. sat./sunday. I really need to fix my schedule. This assert thing confused me at first, still not sure if I'm headed in the right direction when it comes to testing. Let's see if I totally screwed up there..

Also tried to fix the other issues:
- adapted filenames
- returned function values and did `console.log` only those values (to improve testability)
- included function parameters to change triangle/chessb. grid
- used `process.argv` to receive parameters from the console: Question here: So far it works with "node *filename* *param1* *param2* in windows. I found if I was to use syntax like "$ chessboard --symbol #" I need to import a module like "https://www.npmjs.com/package/command-line-args" or is it just a question of using windows vs. using linux? 

Really appreciate the feedback, the first issue already helped me a lot to get to stuff I neglected so far.

**Comment by cideM** [comment]
I don't know much about windows CLI to be honest. The `--` is used, in linux, to separate options from parameters and is usually used when parameters have symbols that can be interpreted like options.

If you do `node filename` then you're running the program `node` with the paramater `filename`. Another option is to use https://stackoverflow.com/questions/20638520/appropriate-hashbang-for-node-js-scripts `#!/usr/bin/env node` that tells the shell which interpreter to use. In that case, you can just do `filename` and the shell reads that special first line and knows to run this with the program found at the path `usr/bin/env node`. Again not sure about windows here.
