### ISSUE TITLE
Write chessboard without for/while/forEach and without `let` and `var`

### ISSUE THREAD

**Issue by cideM** [P215W/eloqJs#2]
Don't use loops, don't mutate. Hint, look at `map` and `reduce`. Two very, very important concepts.
Also, these lines look a little odd, don't they? Seems like your programming language of choice should make stuff like this easier.

```
const lineUn = " " + symbol + " " + symbol + " " + symbol +" " + symbol + "\n";
const lineEv = symbol + " " + symbol + " " + symbol + " " + symbol + " " + "\n";
```

If you align them like so

```
const lineUn = " " + symbol + " " + symbol + " " + symbol + " " + symbol       + "\n";
const lineEv =       symbol + " " + symbol + " " + symbol + " " + symbol + " " +  "\n";
```

you can really see the similarities here. It's almost as if you had a ~array~ list of some sorts, and you want to somehow... ~join~ connect the items with a space and append a newline at the end of each line. The only difference is then where that additional space is located... like... at the start or at the end. Look into functions for arrays or rather the array prototype functions (push, shift, unshift, join etc.). Understand which *mutate* the array and which don't and why that matters to you.

Then look into the https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax which also works with arrays.

And then come back and improve these lines, together with the other stuff in this issue

**Comment by P215W** [comment]
+cideM
Ok tried to implement the chessboard thing with array methods. What do you think? Also added a new minimum thingie from ch.4 from eloquentJs. Although kinda boring, but probably still made rather verbose by me..

**Comment by cideM** [comment]
Cool now you've used `map` and `reduce`, which was what I wanted to achieve. Check this https://repl.it/@cideM/ColossalPeachpuffExpertise for a slightly different version. The idea here is that I created two functions I can test individually (and potentially reuse). Also note how the function uses `slice` to construct two slightly different lines from the same basic template. Anyhow, I think you can move on now :)
